2024-09-26 13:51:49,523 | WARNING | "Неверный тип данных для объекта Runner".
Traceback (most recent call last):
  File "C:\Users\Aleksandr\PycharmProjects\Module_No2._Operators\Module_No2._Operators\module_12\tests_12_4.py", line 74, in test_run
    petya = Runner(5)
            ^^^^^^^^^
  File "C:\Users\Aleksandr\PycharmProjects\Module_No2._Operators\Module_No2._Operators\module_12\rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-09-26 13:51:49,525 | WARNING | "Неверная скорость для Runner".
Traceback (most recent call last):
  File "C:\Users\Aleksandr\PycharmProjects\Module_No2._Operators\Module_No2._Operators\module_12\tests_12_4.py", line 50, in test_walk
    vasya = Runner('Vasya', -5)
            ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksandr\PycharmProjects\Module_No2._Operators\Module_No2._Operators\module_12\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
